djangoecommerce1/ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [

    path('addcart/<int:p>', views.add_cart, name='add_cart'),
    path('minuscart/<int:p>', views.minus_cart, name='minus_cart'),
    path('deletecart/<int:p>', views.delete_cart, name='delete_cart'),
    path('cartview/',views.cartview,name='cartview'),
    path('orderform/',views.orderform,name='orderform'),
    path('orderview/',views.orderview,name='orderview'),

]

djangoecommerce1/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoecommerce1/ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [

    path('',views.searchresult,name='searchresult'),
]

djangoecommerce1/ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('allproducts/<slug:s>',views.allproducts,name='allproducts'),
    path('productdetails/<slug:p>',views.productdetails,name='productdetails'),
    path('login/', views.user_login, name="login"),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name="logout"),

]

djangoecommerce1/ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

# Create your models here.

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateField(auto_now_add=True)
    active=models.BooleanField(default=True)
    def __str__(self):
        return self.products.name

    def subtotal(self):
        return self.quantity*self.products.price

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    noofitems=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def subtotal(self):
        return self.noofitems*self.products.price

class Account(models.Model):
    acctype=models.CharField(max_length=20)
    accno=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return self.accno

djangoecommerce1/ecommerce/search/models.py
from django.db import models

# Create your models here.

djangoecommerce1/ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Category,Product
from cart.models import Cart,Order,Account
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required()
def add_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity+=1
        cart.save()

    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,products=product,quantity=1)
        cart.save()
    return redirect('cart:cartview')

@login_required()
def cartview(request):
    total=0
    user=request.user
    try:
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price
    except Cart.DoesNotExist:
        pass

    return render(request,'cart.html',{'cart':cart,'total':total})

@login_required()
def minus_cart(request,p):
    product = Product.objects.get(id=p)
    user = request.user
    try:
        cart = Cart.objects.get(products=product, user=user)
        if cart.quantity>1:
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()

    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')

@login_required()
def delete_cart(request,p):
    product = Product.objects.get(id=p)
    user = request.user
    try:
        cart = Cart.objects.get(products=product, user=user)
        cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')


@login_required()
def orderform(request):
    total = 0
    if(request.method=="POST"):
        a=request.POST['a']
        p = request.POST['p']
        n = request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.products.price
        ac=Account.objects.get(accno=n)
        if (ac.amount >= total):
            ac.amount=ac.amount-total
            ac.save()
            for i in cart:
                o=Order.objects.create(user=u,products=i.products,address=a,phone=p,order_status="paid",noofitems=i.quantity)
                i.products.stock=i.products.stock-i.quantity
                i.products.save()
                o.save()
            cart.delete()
            msg="ordered successfully"
            return render(request,'ordrdetails.html',{'msg':msg,'total':total})
        else:
            msg= "insufficiant Amount "
            return render(request, 'ordrdetails.html', {'msg': msg})
    return render(request,'orderform.html')

@login_required()
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u,order_status="paid")
    return render(request,'ordeview.html',{'o':o,'name':u.username})

djangoecommerce1/ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
from django.contrib.auth.decorators import login_required


def searchresult(request):
    query=""
    r=None
    if(request.method=="POST"):
        query=request.POST.get('q')
        if(query):
            r=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'r':r})

djangoecommerce1/ecommerce/templates/allproducts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid">
    <div class="container-fluid">
       <img src="{{c.image.url}}" height="400px" width="100%">
    </div>
    <div>
    <h1 style="text-transform:uppercase;">{{c.name}}</h1>
    <p style="text-align:justify;">{{c.description}}</p>
    </div><br>
    <div class="container-fluid" style="margin-bottom:100px;">
    <div class="row "><br><br>
        {%for i in p %}
        <div class=" col-md-3 mb-5">
            <div class="card" style="border-radius:20px;overflow:hidden">

                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body " style="position:relative">
                 <h5 class="card-title" style="text-transform:uppercase;">{{i.name}}</h5>

                    <p class="card-text" style="">PRICE:<span class="text-primary">{{i.price}}</span></p><br><br>
                <div style="display:flex;justify-content:center;align-items:center;">
                 <a href="{% url 'shop:productdetails' i.slug %}" class="btn btn-primary" style="position:absolute;bottom:20px;">DETAILS</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div></div>
</div>

{% endblock %}

djangoecommerce1/ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ecommerce</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--    google font link-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">

<!--    font-awesome link for icons-->
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


</head>
<body>
<div class="container-fluid">
<header>
    <center><img src="{% static 'img/l.webp' %}" alt="img" height="100px" width="100px"></center><br>
</header>
<header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
        <img src="{% static 'img/l.webp' %}" alt="img" height="30px" width="30px" class="d-inline-block align-text-top">
        NEJ</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:home' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i style="font-size:20px;" class="fa-solid fa-cart-shopping"></i>{{item_count}}</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>

           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          {% endif %}
        </ul>


      <form method="POST" class="d-flex" action="{% url 'search:searchresult' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit">Search</button>
      </form>

        <ul class="navbar-nav p-1">
        <li >

            {% if user.is_authenticated %}
                <a>{{user.username}}</a>
            {% endif %}
        </li>
        </ul>

    </div>
  </div>
</nav>
</header>


    {% block content %}
    {% endblock %}


<footer class="footer">
    <div>
        <p><i class="fa-regular fa-copyright"></i> NEJ pvt ltd.All rights reserved</p>
    </div>
</footer>

</div>
</body>
</html>

djangoecommerce1/ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid" style="margin-bottom:100px">
    {% if not cart %}
    <div class="text-center" style="margin-bottom:100px">
        <h1 class="text-center">Cart is Empty</h1>
        <strong><a href="{% url 'shop:home' %}" class="btn btn-primary ">Continue Shopping</a> </strong>
    </div>

     {% else%}


<div class="row">
    <h1 class="text-center">Shopping cart</h1>
  <div class="col-xl-6">
    <table class="table table-bordered">
     <tr>
      <th colspan="5" class="text-center"> cart items</th>
       {% for i in cart %}
     </tr>
     <tr>
      <td><img src="{{i.products.image.url}}" height="100px" width="100px"></td>
      <td><strong>{{i.products.name}}</strong></td>
      <td>
          <p><strong>ProductsId:</strong>{{i.products.id}}</p>
          <p><strong>Unit Price:</strong>{{i.products.price}}</p>
      <p><strong>Quantity:</strong>{{i.quantity}}*{{i.products.price}}</p>
      </td>
         <td><strong>Subtotal:</strong>{{i.subtotal}}</td>
         <td>
             {% if i.quantity < i.products.stock %}
             <a href="{% url 'cart:add_cart' i.products.id %}"><i class="fa-solid fa-circle-plus text-success"></i></a>
             <a href="{% url 'cart:minus_cart' i.products.id %}"><i class="fa-solid fa-circle-minus text-primary"></i></a>
             <a href="{% url 'cart:delete_cart' i.products.id %}"><i class="fa-solid fa-trash text-danger"></i></a>

             {% else %}
             <a href="{% url 'cart:minus_cart' i.products.id %}"><i class="fa-solid fa-circle-minus text-primary"></i></a>
             <a href="{% url 'cart:delete_cart' i.products.id %}"><i class="fa-solid fa-trash text-danger"></i></a>
             {% endif %}

         </td>
     </tr>
        {% endfor %}
    </table>
  </div>
    <div class="col-xl-6" style="position:relative;">
        <table class="table table-bordered text-center">
            <tr><th colspan="5" class="text-center">Check Out</th></tr>
            <tr><td> <strong>TOTAL PRICE:</strong>{{total}}</td></tr>
    </table>

        <a href="{% url 'shop:home' %}" class="btn btn-success" style="width:190px;position:absolute;">Continue Shopping</a>
        <a href="{% url 'cart:orderform' %}" class="btn btn-secondary" style="position:absolute;right:10px;width:190px">Place Order</a>

    </div>

</div>
    {% endif %}
</div>
{% endblock %}

djangoecommerce1/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
<img src="{% static 'img/b2.jpg' %}" alt="img" height="600px" width="100%">
</div>

<div class="container-fluid" style="margin-bottom:100px;" >
    <h1 class="text-center"> Our Collections</h1>
    <p style="text-align:justify;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>

<div class="container">
    <div class="row "><br><br>
        {%for i in c %}
        <div class=" col-md-4 p-3" style="">
            <div class="card" style="height:370px;">
                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body" style="position:relative">
                 <h5 class="card-title text-center" style="text-transform:uppercase;">{{i.name}}</h5>
<!--                 <p class="card-text" style="">RATING:{{i.rating}}</p>-->
                    <div style="display:flex;justify-content:center;align-items:center;">
                <a href="{% url 'shop:allproducts' i.slug %}" class="btn btn-primary" style="position:absolute;bottom:20px">Products</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

djangoecommerce1/ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<h2>log in</h2>
<div >
<form method="POST" enctype="multipart/form-data" class="form form-center p-2 " style="width:35%">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="Enter Username">
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter password">
    </div>
    <div class="mb-3">
        <center><input type="submit" class="btn btn-primary" value="login"></center>
    </div>
</form>
    {% if messages %}
    {% for i in messages%}
    <ul class="messages">
        <li>{{i}}</li>
    </ul>
    {%endfor%}
    {% endif%}
</div>
{% endblock%}

djangoecommerce1/ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>

<form method="POST" class="p-2 " enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="Enter address">
  </div>
    <div class="mb-3">
    <label class="form-label">Phone number</label>
    <input type="number" class="form-control" name="p" placeholder="Enter phone number">
  </div>
    <div class="mb-3">
    <label class="form-label">Account no</label>
    <input type="number" class="form-control" name="n" placeholder="Enter account number">
  </div>
    <div class="mb-3">
    <input type="submit" class="btn btn-primary">

   </div></form>

</div>
{% endblock %}

djangoecommerce1/ecommerce/templates/ordeview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <h5 class="text-center">Name of the Customer:{{name}}</h5>
        {% for i in o %}
        <div class="col-sm-5 py-3" style="border:2px solid gray">
          <center><img src="{{i.products.image.url}}" height="200px" width="200px"></center>
        </div>
        <div class="col-sm-7 py-3 text-center" style="border:2px solid gray">
            Delivery Address :{{i.address}}<br>
            Phone number :{{i.phone}}<br>
            {{i.products.name}}<br>
            {{i.products.price}}<br>
            Quantity Ordered:{{i.noofitems}}<br>
            Subtotal:{{i.subtotal}}<br>
            <strong class="text-primary">Ordered on {{i.date_added}}</strong><br>
            <strong class="text-success">Delivery status :{{i.delivery_status}}</strong>
    </div>
        {% endfor %}
    </div></div>
{% endblock %}

djangoecommerce1/ecommerce/templates/ordrdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2 class="text-center text-success">{{msg}}</h2>
    <h5 class="text-center text-danger">Thank you...</h5>
    <p class="text-center"><a href="{% url 'shop:home' %}" class="btn btn-primary ">Continue Shopping</a> </p>

</div>
{% endblock %}

djangoecommerce1/ecommerce/templates/productdetails.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<h1>DETAILS</h1>

<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <div class=" col-md-6 mt-5" >
            <img src="{{p.image.url}}" class="img-top" alt="..." height="80%" width="80%">
        </div>
        <div class=" col-md-6 bg-light mt-5 ">
            <h2 class="card-title" style="text-transform:uppercase;"><b>{{p.name}}</b></h2><br>
            <h3>PRICE:<span class="text-primary">{{p.price}}</span></h3>
            <h3>DESCRIPTION:</h3>
            <p style="text-align:justify">{{p.description}}</p>

            {% if p.stock <= 0 %}
                <h2>Out of stock</h2>
            {% else %}
                 <a href="{% url 'cart:add_cart' p.id %}" class="btn btn-success">ADD TO CART</a>
            {% endif %}
        </div>

    </div>
</div>
{% endblock %}

djangoecommerce1/ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<h2>register</h2>

<form method="POST" class="p-2 " enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Username">
  </div>
    <div class="mb-3">
    <label class="form-label">First name</label>
    <input type="text" class="form-control" name="f" placeholder="Enter first name">
  </div>
    <div class="mb-3">
    <label class="form-label">last name</label>
    <input type="text" class="form-control" name="l" placeholder="Enter last name">
  </div>
    <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="e" placeholder="Enter Email">
  </div>
    <div class="mb-3">
    <label class="form-label">password</label>
    <input type="password" class="form-control" name="p" placeholder="Enter password">
  </div>
   <div class="mb-3">
    <label class="form-label">confirm password</label>
    <input type="password" class="form-control" name="cp" placeholder="Enter password again">
 </div>
    <div class="mb-3">
    <input type="submit" class="btn btn-primary">

   </div></form>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
{% endblock%}

djangoecommerce1/ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div><h4 class="text-center">You have searched for <span class="text-success">'{{query}}'</span></h4></div>
  <div CLASS="container text-center">
      <h6>SEARCH RESULTS</h6>

    <div class="container-fluid" style="">
    <div class="row "><br><br>
        {%for i in r %}
        <div class=" col-md-3 mb-5" style="">
            <div class="card" style="border-radius:20px;overflow:hidden">
                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body " style="position:relative">
                 <h5 class="card-title" style="text-transform:uppercase;">{{i.name}}</h5>

                    <p class="card-text" style="">PRICE:<span class="text-primary">{{i.price}}</span></p><br><br>
                    <div style="display:flex;justify-content:center;align-items:center;">
                     <a href="{% url 'shop:productdetails' i.slug %}" class="btn btn-primary" style="position:absolute;bottom:20px;">DETAILS</a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <h5 class="text-center text-danger">0 Results FOUND</h5>
        {% endfor %}
    </div></div> </div>


{% endblock%}